name: Build and Publish Binaries 🛠️

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  packages: write

concurrency:
  group: binaries-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: uname -s
      - name: Install dependencies
        run: | 
          sudo apt-get update 
          sudo apt-get install -y build-essential clang-tools-14 git libssl-dev pkg-config protobuf-compiler libudev-dev
          sudo apt-get clean
      - name: Setup Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Setup rust 1.85.1
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build
        run: make
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: migrate-masp-events
          draft: true